---
language: python
python: "2.7"
sudo: true

before_install:
  - echo "localhost ansible_connection=local" >> test.yml

install:
  # Install ansible
  - pip install ansible

script:
  # Check the role/playbooks syntax
  - rvm use 1.9.2 && ansible-playbook -i test.yml ansible/site.yml